### ISSUE TITLE
a demonstration of beachmat on analyzing the 1M cells from 10x

### ISSUE THREAD

**Issue by Xiaojieqiu** [tatami-inc/archive-beachmat#4]
Hi Aaron, 

Can we make a tutorial or something to demonstrate the usage of beachmat in analyzing the 1M cells from 10x? Simple tSNE can be used for analyzing this data. 

The data is here: 
https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.3.0/1M_neurons

I may be able to add trajectory inference, etc. using Monocle too (This part may require some more algorithmic development).

**Comment by LTLA** [comment]
I've committed some scripts for doing so, see `real/10X` in https://github.com/LTLA/MatrixEval2017. However, it is seriously tough work. Just computing the row and column sums takes about 10 minutes. Calculation of size factors takes several hours. I can't even begin to imagine how long it would take to do anything more complicated - I can only hope that _t_-SNE doesn't compute the full distance matrix.

**Comment by Xiaojieqiu** [comment]
It seems like Alex from Fabian's lab did some nice analysis on this dataset using tSNE and the diffusion maps. He reported that tSNE run only takes 4 hours (with top 1k dispersion genes) and diffusion maps takes about 10 hours (See the link below). Maybe we can get some inspiration from there? 
 
https://github.com/theislab/scanpy_usage/tree/master/170522_visualizing_one_million_cells

**Comment by Xiaojieqiu** [comment]
btw, does beachmat use OMP for parallel calculation?

**Comment by LTLA** [comment]
_beachmat_ itself doesn't do any calculations, it literally just provides an C++ API for matrix row/column access. Developers can then use the data in their own functions, with or without parallelization. Parallel access requires some care, though, as each `*_matrix` instance caches some intermediate data structures. This might cause race conditions if multiple threads request data from the same instance simultaneously. The solution is either to make a copy of the instance for each thread, which is generally fairly cheap as the underlying data is not copied; or to throw in some mutexes for data access. 

I saw the same _t_-SNE result on a poster last week - quite strange-looking wispy patterns, something we don't usually see in our _t_-SNE plots. I would have expected nice clusters of different cell types. Anyway, staring at the _Rtsne_ documentation suggests that, maybe, it doesn't actually compute the full distance matrix when the KD-tree approximations are operating. So if we can reduce the dimensions enough to obtain a dense matrix in memory, we might be able to use the package as-is.

**Comment by Xiaojieqiu** [comment]
yeah. I knew that beachmat itself is designed for providing a "container" for data storage and access. I think, however, having an analysis demonstration of beachmat on this dataset will be valuable and really test its limits. I agreed that, running tSNE or trajectory reconstruction is probably something the beachmat users, like me, should try on our side. I will start to use beachmat for running tSNE on this dataset and get back to you. Thanks for the other explanation on parallel too!

**Comment by LTLA** [comment]
Cool. Just to be clear, though:

1. _beachmat_ "users" are really package developers; I don't expect the average R user to write C++ extensions, especially if they need to link to a shared library.
2. Expect to see a slight performance hit when column-accessing simple matrices. This is because _beachmat_ copies column data into a new vector for use by the calling function; this is necessary for the interface to be completely agnostic with the other matrix representations, but is not actually required for simple matrices as you can just provide a pointer to the start of each column.
3. A similar point applies to accessing sparse matrices. For a given algorithm, you can usually write a sparse-specific version that avoids dealing with the zero counts. This is faster, but is obviously more painful if you have to write (and test, and maintain!) two copies of every function - I would only consider doing this for very common functions, e.g., `colSums`.

**Comment by LTLA** [comment]
_beachmat_ is now on Bioconductor and pretty stable (though we're still fighting with the Windows build, which isn't quite working properly at the moment). So I'll close this issue; let me know if you have any problems with using it. Note that points 2 and 3 in the above message no longer apply.
